config/routes.rb
Timetracker::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :dashboard
  resources :features, :only => :index
  resources :accounts

  resources :subscriptions do
    get :confirm_subscription, :on => :collection
    get :cancel, :on => :collection
  end

  resources :company
  resources :company_users, :except => [:index, :edit, :update]

  resources :projects do
    resources :tasks
    resources :users, :controller => :project_users
    get :archived, :on => :collection
  end

  resources :tasks

  resources :timeslips do
    post :get_tasks, :on => :collection
    post :get_users, :on => :collection
  end
  match "/timeslips/:year/:month/:day" => "timeslips#index", :as => "timeslips_date"

  resources :reports do
    post :generate_report, :on => :collection
    post :view_report, :on => :collection
  end

  resources :webhooks, :only => [:receive_payload] do
    post :receive_payload, :on => :collection
  end

  resources :bills
  resources :support do
    get :privacy, :on => :collection
  end
  match 'support' => 'support#create', :as => 'support', :via => :post
  resources :developer

  root :to => "home#index"
  match 'home/plans' => 'home#plans'

  # API
  namespace :api do
    namespace :v1 do
      post 'login' => 'users#login'
    end
  end

end

app/views/shared/_account_sidebar.html.haml
.title-area
  %h1 Navigation
.area
  %ul{ :class => "nav nav-list" }
    %li
      %a{ :href => accounts_path }
        %i{ :class => "icon-home" }
        My Account
    - if current_user.owns_company
      %li
        %a{ :href => subscriptions_path }
          %i{ :class => "icon-asterisk" }
          Payments

app/views/shared/_bills_sidebar.html.haml
.title-area
  %h1 Navigation
.area
  %ul{ :class => "nav nav-list" }

app/views/shared/_developer_sidebar.html.haml
.title-area
  %h1 Navigation
.area
  %ul{ :class => "nav nav-list" }
    %li
      %a{ :href => developer_index_path }
        %i{ :class => "icon-home" }
        Developer Home
.title-area
  %h1 API Status
.area#developers
  %ul{ :class => "nav nav-list" }
    %li
      %span.label.label-success Create application
    %li
      %span.label.label-success Login to TimeTracker
    %li
      %span.label.label-important Dashboard
    %li
      %span.label.label-important Account
    %li
      %span.label.label-important Company
    %li
      %span.label.label-important Projects
    %li
      %span.label.label-important Tasks
    %li
      %span.label.label-important Timeslips
    %li
      %span.label.label-important Manage reports

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  %div.alert{ :class => twitterized_type(type) }
    %a.close{:href => "#", :"data-dismiss" => "alert"} ×
    = message

app/views/shared/_sidebar.html.haml
.title-area
  %h1 Navigation
.area
  %ul{ :class => "nav nav-list" }
    %li
      = link_to dashboard_index_path do
        %i.icon-home
        Dashboard
      - if current_user
        - if !current_user.sub_account
          = link_to company_index_path do
            %i.icon-user
            Company
        - if current_user.company && !current_user.sub_account
          = link_to projects_path do
            %i.icon-th-list
            Projects
        - if current_user.company && ((current_user.company.projects.count > 0 && !current_user.sub_account) || current_user.company.tasks_count > 0)
          = link_to tasks_path do
            %i.icon-ok
            Tasks
          = link_to "/timeslips/#{Date.today.year}/#{Date.today.month}/#{Date.today.day}" do
            %i.icon-time
            Timeslips
          = link_to reports_path do
            %i.icon-folder-open
            Reports