config/routes.rb
Timetracker::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :dashboard
  resources :features, :only => :index
  resources :accounts

  resources :subscriptions do
    get :confirm_subscription, :on => :collection
    get :cancel, :on => :collection
  end

  resources :company
  resources :company_users, :except => [:index, :edit, :update]

  resources :projects do
    resources :tasks
    resources :users, :controller => :project_users
    get :archived, :on => :collection
  end

  resources :tasks

  resources :timeslips do
    post :get_tasks, :on => :collection
    post :get_users, :on => :collection
  end
  match "/timeslips/:year/:month/:day" => "timeslips#index", :as => "timeslips_date"

  resources :reports do
    post :generate_report, :on => :collection
    post :view_report, :on => :collection
  end

  resources :webhooks, :only => [:receive_payload] do
    post :receive_payload, :on => :collection
  end

  resources :bills
  resources :support do
    get :privacy, :on => :collection
  end
  match 'support' => 'support#create', :as => 'support', :via => :post
  resources :developer

  root :to => "home#index"
  match 'home/plans' => 'home#plans'

  # API
  namespace :api do
    namespace :v1 do
      post 'login' => 'users#login'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home"
  def index
  end
  def plans
    @plans = Plan.find(:all)
  end
end

app/views/home/_plan.html.haml
.subscription
  .header
    %h2.title= plan.title.upcase
    %p.description= plan.description
  .price
    %span.currency £
    %span.value= plan.value
    %span.duration= plan.duration
  .details
    %p= "#{plan.project_count} Projects"
    %p= "#{plan.user_count} Users"
    %p Technical Support
    %a.btn.btn-success{ :href => new_user_registration_path, :target => "_blank" } Try For Free

app/views/home/index.html.haml
- content_for(:title, 'TerraTimer')
.main
  .home-intro
    %h1 Simple time tracking and report generation
    .area
      %table.table
        %tr
          %td
            .thumbnail= image_tag("screen1.png")
            %p Create your own projects and tasks
          %td
            .thumbnail= image_tag("screen2.png")
            %p Give users easy access to start timing their tasks
          %td
            .thumbnail= image_tag("screen3.png")
            %p Analyse time and create reports
      = link_to "See Features", features_path, :class => "btn btn-success btn-large"
.main
  .area
    %p TerraTimer makes this simple by giving the ability to record expenses and have them turned into PDFs along with the company name, personal details and other information.
    %hr.soften
    %p= link_to "See Plans & Pricing", home_plans_path, :class => "btn btn-success btn-large"
  %hr.soften
  .bottom
    - if current_user
      %p= link_to "Dashboard", dashboard_index_path, :class => "btn btn-primary btn-large"
    - else
      %p
        = link_to "Login", new_user_session_path, :class => "btn btn-primary btn-large"
        = link_to "Try For Free", new_user_registration_path, :class => "btn btn-primary btn-large"

app/views/home/plans.html.haml
- content_for(:title, 'TimeTracker - Plans & Pricing')
.main
  .area
    .subscriptions
      %h2 Available Plans
      %br
      - @plans.each do |plan|
        = render :partial => "home/plan", :locals => { :plan => plan }