config/routes.rb
Timetracker::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :dashboard
  resources :features, :only => :index
  resources :accounts

  resources :subscriptions do
    get :confirm_subscription, :on => :collection
    get :cancel, :on => :collection
  end

  resources :company
  resources :company_users, :except => [:index, :edit, :update]

  resources :projects do
    resources :tasks
    resources :users, :controller => :project_users
    get :archived, :on => :collection
  end

  resources :tasks

  resources :timeslips do
    post :get_tasks, :on => :collection
    post :get_users, :on => :collection
  end
  match "/timeslips/:year/:month/:day" => "timeslips#index", :as => "timeslips_date"

  resources :reports do
    post :generate_report, :on => :collection
    post :view_report, :on => :collection
  end

  resources :webhooks, :only => [:receive_payload] do
    post :receive_payload, :on => :collection
  end

  resources :bills
  resources :support do
    get :privacy, :on => :collection
  end
  match 'support' => 'support#create', :as => 'support', :via => :post
  resources :developer

  root :to => "home#index"
  match 'home/plans' => 'home#plans'

  # API
  namespace :api do
    namespace :v1 do
      post 'login' => 'users#login'
    end
  end

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  validates_presence_of :reference_id
  validates_presence_of :bill_date
  validates_presence_of :due_date
  validates_presence_of :value
  belongs_to :user
  belongs_to :company
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_filter :authenticate_user!, :redirect_sub_account, :redirect_company

  def index
    @bills = Bill.where(:company_id => current_company)
  end

  def new
    @bill = Bill.new(:bill_date => Date.today, :due_date => Date.today)
  end

  def edit
    @bill = Bill.find(params[:id])
  end

  def show
    @bill = Bill.find(params[:id])
  end

  def create
    @bill = Bill.new(params[:bill])
    @bill.user = current_user
    @bill.company = current_company
    if @bill.save
      redirect_to(bills_path, :notice => "The bill was successfully created.")
    else
      render :action => :new
    end
  end

  def update
    @bill = Bill.find(params[:id])
    if @bill.update_attributes(params[:bill])
      redirect_to(bills_path, :notice => "The bill was successfully updated.")
    else
      render :action => "edit"
    end
  end

  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to(bills_path, :notice => "The bill was successfully removed.") }
      format.js
    end
  end

end

app/views/bills/destroy.js.erb
$("tr#<%= @bill.id %>").remove();

app/views/bills/edit.html.haml
- content_for(:title, 'Edit Bill')
.row
  .span2
    = render :partial => "shared/bills_sidebar"
  .span9
    .title-area
      %h1 End Bill
    .area
      = simple_form_for(@bill, :url => @bill, :html => {:class => 'form-horizontal' }) do |f|
        = f.input :reference_id, :autofocus => true, :label => 'Reference'
        = f.input :bill_date, :as => :string, :input_html => { :value => @bill.bill_date.strftime("%d/%m/%Y") }
        = f.input :due_date, :as => :string, :input_html => { :value => @bill.due_date.strftime("%d/%m/%Y") }
        = f.input :value, :placeholder => "0.00", :required => true
        = f.input :comment, :label => "Comments"
        = f.input :paid
        = f.button :submit, "Update Bill", :class => 'btn btn-primary'
        = link_to "Back", :back, :class => 'btn'

:javascript
  $(function() {
    $("#bill_bill_date").datepicker({format: 'dd/mm/yyyy'});
    $("#bill_due_date").datepicker({format: 'dd/mm/yyyy'});
  });

app/views/bills/index.html.haml
- content_for(:title, 'Bills')
.row
  .span2
    = render :partial => "shared/bills_sidebar"
  .span9
    .title-area
      %h1 Bills
    .area
      %table.table.table-striped
        %thead
          %tr
            %th Reference
            %th Bill Date
            %th Due Date
            %th Value
            %th Comment
            %th Status
            %th
        - @bills.each do |bill|
          %tr{ :id => bill.id}
            %td= bill.reference_id
            %td= bill.bill_date.strftime("%e %b %y")
            %td= bill.due_date.strftime("%e %b %y")
            %td= number_with_precision(bill.value, :precision => 2)
            %td= bill.comment
            %td
              - if bill.paid
                %span.label.label-success Paid
              - elsif bill.due_date < DateTime.now
                %span.label.label-important Overdue
              - else
                %span.label.label-warning Unpaid
            %td
              = link_to bill_path(bill), :class => "btn" do
                %i.icon-search
                Show
              = link_to edit_bill_path(bill), :class => "btn" do
                %i.icon-pencil
                Edit
              = link_to bill, :confirm => "Are you sure?", :method => :delete, :remote => true, :class => "btn btn-danger" do
                %i.icon-trash.icon-white
                Delete
      = link_to new_bill_path, :class => "btn btn-primary" do
        %i.icon-plus.icon-white
        Add Bill

app/views/bills/new.html.haml
- content_for(:title, 'New Bill')
.row
  .span2
    = render :partial => "shared/bills_sidebar"
  .span9
    .title-area
      %h1 Create Bill
    .area
      = simple_form_for(@bill, :url => @bill, :html => {:class => 'form-horizontal' }) do |f|
        = f.input :reference_id, :autofocus => true, :label => 'Reference'
        = f.input :bill_date, :as => :string, :input_html => { :value => @bill.bill_date.strftime("%d/%m/%Y") }
        = f.input :due_date, :as => :string, :input_html => { :value => @bill.due_date.strftime("%d/%m/%Y") }
        = f.input :value, :placeholder => "0.00", :required => true
        = f.input :comment, :label => "Comments"
        = f.input :paid
        = f.button :submit, "Create Bill", :class => 'btn btn-primary'
        = link_to "Back", :back, :class => 'btn'

:javascript
  $(function() {
    $("#bill_bill_date").datepicker({format: 'dd/mm/yyyy'});
    $("#bill_due_date").datepicker({format: 'dd/mm/yyyy'});
  });

app/views/bills/show.html.haml
- content_for(:title, "View Bill")
.row
  .span2
    = render :partial => "shared/bills_sidebar"
  .span9
    .title-area
      %h1
        Bill
        - if @bill.paid
          %span.label.label-success Paid
        - elsif @bill.due_date < DateTime.now
          %span.label.label-important Overdue
        - else
          %span.label.label-warning Unpaid
    .area
      .well
        %p= "Reference: "+@bill.reference_id
        %p= "Comment: "+@bill.comment
        %p= "Due Date: "+@bill.due_date.strftime("%e %b %y")
        %p= "Bill Date: "+@bill.bill_date.strftime("%e %b %y")
        %p= "Bill Value: "+number_with_precision(@bill.value, :precision => 2)
      = link_to edit_bill_path(@bill), :class => "btn btn-primary" do
        %i.icon-pencil.icon-white
        Edit
      = link_to bills_path, :class => "btn" do
        %i.icon-th-list
        View All Bills