config/routes.rb
Timetracker::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :registrations => :registrations }

  resources :dashboard
  resources :features, :only => :index
  resources :accounts

  resources :subscriptions do
    get :confirm_subscription, :on => :collection
    get :cancel, :on => :collection
  end

  resources :company
  resources :company_users, :except => [:index, :edit, :update]

  resources :projects do
    resources :tasks
    resources :users, :controller => :project_users
    get :archived, :on => :collection
  end

  resources :tasks

  resources :timeslips do
    post :get_tasks, :on => :collection
    post :get_users, :on => :collection
  end
  match "/timeslips/:year/:month/:day" => "timeslips#index", :as => "timeslips_date"

  resources :reports do
    post :generate_report, :on => :collection
    post :view_report, :on => :collection
  end

  resources :webhooks, :only => [:receive_payload] do
    post :receive_payload, :on => :collection
  end

  resources :bills
  resources :support do
    get :privacy, :on => :collection
  end
  match 'support' => 'support#create', :as => 'support', :via => :post
  resources :developer

  root :to => "home#index"
  match 'home/plans' => 'home#plans'

  # API
  namespace :api do
    namespace :v1 do
      post 'login' => 'users#login'
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  validate :check_project_limit, :on => :update
  validate :check_project_creation, :on => :create
  belongs_to :company
  validates_presence_of :name
  has_many :tasks, :dependent => :destroy
  has_many :project_users, :dependent => :destroy
  has_many :users, :through => :project_users
  has_many :timeslips, :dependent => :destroy

  def to_s
    name
  end

  def available_statuses
    ["Active","Completed","Cancelled"]
  end

  private

  def check_project_limit
    if archived_was == true && company.plan.project_count <= company.projects.where(:archived => false).count
      self.errors[:base] << "You have reached your project limit. If you wish to add more projects, please upgrade your account."
      return false
    end
  end

  def check_project_creation
    if company.plan.project_count <= (company.projects.count - company.projects.where(:archived => true).count)
      self.errors[:base] << "You have reached your project limit. If you wish to add more projects, please upgrade your account."
      return false
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :redirect_company, :redirect_sub_account
  
  def index
    @all_projects = Project.where(:company_id => current_company.id)
    @projects = @all_projects.where(:archived => false)
    @archived_projects_count = @all_projects.where(:archived => true).count
  end

  def archived
    @projects = Project.where(:company_id => current_company.id, :archived => true)
  end

  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks
  end
  
  def new
    @project = Project.new
  end
  
  def edit
    @project = Project.find(params[:id])
    @archived_count = current_user.projects.where(:archived => true).count
  end
  
  def create
    @project = Project.new(params[:project])
    @project.company = current_company
    if @project.save
      @project_user = ProjectUser.create(:project_id => @project.id, :user_id => current_user.id)
      redirect_to(project_path(@project), :notice => "The project #{@project.name} was successfully created.")
    else
      render :action => "new"
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to(projects_path, :notice => "The project was successfully updated.")
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to(projects_path, :notice => "The project was successfully removed.") }
      format.js
    end
  end

end

app/views/projects/_edit.html.haml
.modal.hide.fade.in{:id => "project_edit_#{@project.id}"}
  .modal-header
    %button.close{ "data-dismiss" => "modal" } &times;
    %h1 Edit Your Project
  = simple_form_for(@project, :url => @project, :html => {:class => 'form-horizontal' }) do |f|
    .modal-body
      = f.input :name, :required => true, :autofocus => true, :class => 'input-xlarge', :label => 'Project Name'
      = f.input :status, :collection => @project.available_statuses, :include_blank => false
      - if @project.archived && (current_user.projects.count - current_user.projects.where(:archived => true).count) > current_user.company.plan.project_count
        = f.input :archived, :disabled => true
      - else
        = f.input :archived
    .modal-footer
      = f.button :submit, "Update", :class => 'btn btn-primary'
      %a{ :href => "#", :class => "btn", "data-dismiss" => "modal" } Close
:javascript
  id: "#{@project.id}"
  if ($('#project-errors').length > 0) {
    $("#project_edit_" + id).modal('toggle');
  }

app/views/projects/_new.html.haml
.modal.hide.fade.in#project-new
  .modal-header
    %button.close{ "data-dismiss" => "modal" } &times;
    %h1 Create Project
  = simple_form_for(@project, :url => @project, :html => { :class => 'form-horizontal' }) do |f|
    .modal-body
      = f.input :name, :required => true, :autofocus => true, :label => 'Project Name'
      = f.input :status, :collection => @project.available_statuses, :selected => @project.available_statuses[0], :include_blank => false
    .modal-footer
      = f.button :submit, "Create Project", :class => 'btn btn-primary'
      %a{ :href => "#", :class => "btn", "data-dismiss" => "modal" } Close
:javascript
  if ($('#project-errors').length > 0) {
    $("#project-new").modal('toggle');
  }

app/views/projects/archived.html.haml
- content_for(:title, 'Archived Projects')
.row
  .span2
    = render :partial => "shared/sidebar"
  .span9
    .title-area
      %h1 Archived Projects
    .area#projects
      %table.table.table-striped
        %thead
          %tr
            %th ID
            %th Project Name
            %th 
        - @projects.each do |p|
          %tr{ :id => p.id }
            %td= p.id
            %td= p.name         
            %td
              = link_to project_path(p), :class => "btn" do
                %i.icon-search
                Show
              = link_to edit_project_path(p), :remote => true, :class => "btn" do
                %i.icon-pencil
                Edit
              = link_to p, :confirm => "Are you sure?", :method => :delete, :remote => true, :class => "btn btn-danger" do
                %i.icon-trash.icon-white
                Delete
      = link_to "View Unarchived Projects", projects_path, :class => "btn"

app/views/projects/destroy.js.erb
$("tr#<%= @project.id %>").remove();

app/views/projects/edit.html.haml
- content_for(:title, 'Edit Project')
.row
  .span2
    = render :partial => "shared/sidebar"
  .span9
    .title-area
      %h1 Edit Your Project
    .area
      = simple_form_for(@project, :url => @project, :html => {:class => 'form-horizontal' }) do |f|
        - if @project.errors[:base].any?
          %div.alert{ :class => twitterized_type(:error) }
            %a.close{:href => "#", :"data-dismiss" => "alert"} ×
            - @project.errors.full_messages.each do |msg|
              = msg
        = f.input :name, :required => true, :autofocus => true, :class => 'input-xlarge', :label => 'Project Name'
        = f.input :status, :collection => @project.available_statuses, :include_blank => false
        - if @project.archived && (current_user.projects.count - current_user.projects.where(:archived => true).count) > current_user.company.plan.project_count
          = f.input :archived, :disabled => true
        - else
          = f.input :archived
        = f.button :submit, "Update", :class => 'btn btn-primary'
        = link_to "Back", :back, :class => 'btn'

app/views/projects/edit.js.erb
$("#projects").before("<%= escape_javascript(render "edit", :formats => [:html]) %>");
$("#project_edit_<%= params[:id] %>").modal();

app/views/projects/index.html.haml
- content_for(:title, 'Projects')
.row
  .span2
    = render :partial => "shared/sidebar"
  .span9
    .title-area
      %h1 Projects
    .area#projects
      %table.table.table-striped
        %thead
          %tr
            %th Project Name
            %th Status
            %th 
        - @projects.each do |p|
          %tr{ :id => p.id }
            %td= p.name
            %td
              - if p.status == "Active"
                %span.label.label-info= p.status
              - elsif p.status == "Completed"
                %span.label.label-success= p.status
              - else
                %span.label.label-important= p.status
            %td
              = link_to project_path(p), :class => "btn" do
                Show
              = link_to edit_project_path(p), :remote => true, :class => "btn" do
                Edit
              = link_to p, :confirm => "Are you sure?", :method => :delete, :remote => true, :class => "btn btn-danger" do
                Delete
      = link_to "Add Project", new_project_path, :remote => true, :class => "btn btn-primary"
      - if @archived_projects_count > 0
        %hr
        %p
          = "You have #{@archived_projects_count} archived project(s)."
          = link_to "Click here to view archived projects.", archived_projects_path

app/views/projects/new.html.haml
- content_for(:title, 'New Project')
- if @project.errors[:base].any?
  %div.alert#project_errors{ :class => twitterized_type(:error) }
    %a.close{:href => "#", :"data-dismiss" => "alert"} ×
    - @project.errors.full_messages.each do |msg|
      = msg
.row
  .span2
    = render :partial => "shared/sidebar"
  .span9
    .title-area
      %h1 Create Project
    .area
      = simple_form_for(@project, :url => @project, :html => { :class => 'form-horizontal' }) do |f|
        = f.input :name, :required => true, :autofocus => true, :label => 'Project Name'
        = f.input :status, :collection => @project.available_statuses, :selected => @project.available_statuses[0], :include_blank => false
        = f.button :submit, "Create Project", :class => 'btn btn-primary'
        = link_to "Back", projects_path, :class => 'btn'

app/views/projects/new.js.erb
$("#projects").before("<%= escape_javascript(render "new", :formats => [:html]) %>");
$("#project-new").modal();

app/views/projects/show.html.haml
- content_for(:title, @project.name)
.row
  .span2
    = render :partial => "shared/sidebar"
  .span9#projects
    .title-area
      %h1= "#{@project.name} (#{@project.status})"
    .area
      %p
        = link_to projects_path, :class => "btn" do
          %i.icon-th-list
          View All Projects
        - if !@project.archived
          = link_to edit_project_path(@project), :remote => true, :class => "btn" do
            %i.icon-pencil
            Edit Project
        = link_to @project, :confirm => "Are you sure?", :method => :delete, :class => "btn btn-danger" do
          %i.icon-trash.icon-white
          Delete Project
      %h3 Tasks
      = render :partial => "tasks/tasks"
      - if !@project.archived
        = link_to "Add Task", new_project_task_path(@project), :remote => true, :class => 'btn btn-primary'
    .title-area
      %h1 Users
    .area
      - if @project.project_users.count > 0
        = render :partial => "project_users/project_users"
      - else
        %p There are no project users assigned.
      - if !@project.archived
        = link_to "Add Project User", new_project_user_path(@project), :class => 'btn btn-primary'